"use client"

import { useState } from "react"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Zap, Download, ShieldCheck, Gamepad2, Globe, Users } from "lucide-react"
import { useAuth } from "@/firebase"
import { createUserWithEmailAndPassword } from "firebase/auth"
import { useToast } from "@/hooks/use-toast"

export default function LandingPage() {
  const auth = useAuth()
  const { toast } = useToast()
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")
  const [loading, setLoading] = useState(false)

  const handleSignUp = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!auth) return
    setLoading(true)
    try {
      await createUserWithEmailAndPassword(auth, email, password)
      toast({ title: "Account Created", description: "Welcome to Ouroboros. You can now log into the client." })
    } catch (e: any) {
      toast({ variant: "destructive", title: "Signup Failed", description: e.message })
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-background text-foreground selection:bg-accent selection:text-accent-foreground">
      {/* Hero Section */}
      <nav className="flex items-center justify-between p-6 border-b border-border bg-background/50 backdrop-blur-md sticky top-0 z-50">
        <div className="flex items-center gap-2">
          <div className="h-8 w-8 axiom-gradient rounded flex items-center justify-center">
            <Zap className="h-5 w-5 text-white" />
          </div>
          <span className="font-headline font-bold text-xl tracking-tight">OUROBOROS</span>
        </div>
        <div className="flex items-center gap-4">
          <Button variant="ghost" asChild><Link href="/">Admin Dashboard</Link></Button>
          <Button className="axiom-gradient text-white border-0">Play Now</Button>
        </div>
      </nav>

      <main>
        <section className="relative py-24 px-6 overflow-hidden">
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-full bg-[radial-gradient(circle_at_50%_120%,rgba(96,212,255,0.15),transparent)] pointer-events-none" />
          <div className="max-w-6xl mx-auto text-center space-y-8 relative z-10">
            <Badge variant="outline" className="text-accent border-accent py-1 px-4 text-sm">PRE-ALPHA ACCESS</Badge>
            <h1 className="text-6xl md:text-8xl font-headline font-bold tracking-tighter leading-none">
              The Next Evolution of <br />
              <span className="text-accent">Persistent Worlds</span>
            </h1>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              A serverless MMORPG powered by Firebase and Godot. Experience a deterministic world where every tick counts.
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              <Button size="lg" className="axiom-gradient text-white h-14 px-8 text-lg gap-2">
                <Download className="h-5 w-5" /> Download for Android
              </Button>
              <Button size="lg" variant="outline" className="h-14 px-8 text-lg border-accent text-accent hover:bg-accent/10">
                Join Discord
              </Button>
            </div>
          </div>
        </section>

        <section className="py-20 px-6 bg-secondary/10 border-y border-border">
          <div className="max-w-6xl mx-auto grid md:grid-cols-3 gap-12">
            <div className="space-y-4">
              <Globe className="h-10 w-10 text-accent" />
              <h3 className="text-2xl font-headline font-bold">Live World Sync</h3>
              <p className="text-muted-foreground">Deterministic heartbeat engine synchronizes civilization state and entity positions across all clients every minute.</p>
            </div>
            <div className="space-y-4">
              <ShieldCheck className="h-10 w-10 text-accent" />
              <h3 className="text-2xl font-headline font-bold">Secure Transactions</h3>
              <p className="text-muted-foreground">Firestore-backed inventory and trade systems protected by rigorous security rules and AxiomEnforcer logic.</p>
            </div>
            <div className="space-y-4">
              <Users className="h-10 w-10 text-accent" />
              <h3 className="text-2xl font-headline font-bold">Player-Driven Lore</h3>
              <p className="text-muted-foreground">Quest and NPC personalities are dynamically generated by Gemini AI based on real-time world progression.</p>
            </div>
          </div>
        </section>

        <section className="py-24 px-6 max-w-4xl mx-auto">
          <Card className="border-accent/30 bg-card overflow-hidden">
            <div className="grid md:grid-cols-2">
              <div className="p-10 space-y-6 flex flex-col justify-center">
                <h2 className="text-3xl font-headline font-bold">Create Your Account</h2>
                <p className="text-muted-foreground">Register now to secure your display name and join the Ouroboros pioneer fleet.</p>
                <form onSubmit={handleSignUp} className="space-y-4">
                  <div className="space-y-2">
                    <Input 
                      placeholder="Email Address" 
                      type="email" 
                      value={email} 
                      onChange={(e) => setEmail(e.target.value)} 
                      required 
                    />
                  </div>
                  <div className="space-y-2">
                    <Input 
                      placeholder="Password" 
                      type="password" 
                      value={password} 
                      onChange={(e) => setPassword(e.target.value)} 
                      required 
                    />
                  </div>
                  <Button type="submit" className="w-full axiom-gradient text-white" disabled={loading}>
                    {loading ? "Initializing..." : "Register & Download"}
                  </Button>
                </form>
              </div>
              <div className="bg-secondary/30 p-10 flex flex-col items-center justify-center text-center gap-6 border-l border-border">
                <div className="h-32 w-32 axiom-gradient rounded-full flex items-center justify-center shadow-[0_0_50px_rgba(96,212,255,0.3)]">
                  <Gamepad2 className="h-16 w-16 text-white" />
                </div>
                <div>
                  <div className="text-2xl font-headline font-bold mb-1">Mobile Client</div>
                  <div className="text-sm text-muted-foreground">v0.9.4a-stable</div>
                </div>
                <div className="space-y-2 w-full">
                  <Badge variant="secondary" className="w-full justify-center">ANDROID APK</Badge>
                  <Badge variant="secondary" className="w-full justify-center opacity-50">iOS (COMING SOON)</Badge>
                </div>
              </div>
            </div>
          </Card>
        </section>
      </main>

      <footer className="p-12 border-t border-border text-center text-sm text-muted-foreground">
        &copy; 2025 Ouroboros MMO Labs. All rights reserved. Powered by Axiom Core.
      </footer>
    </div>
  )
}